

const typesOfWorks = {
    Architecture: [
        { label: "Residential Architecture", value: "Residential Architecture" },
        { label: "Commercial Architecture", value: "Commercial Architecture" },
        { label: "Landscape Architecture", value: "Landscape Architecture" },
        { label: "Industrial Architecture", value: "Industrial Architecture" },
        { label: "Interior Architecture", value: "Interior Architecture" },
        { label: "Urban Design", value: "Urban Design" },
        { label: "Sustainable Architecture", value: "Sustainable Architecture" },
        { label: "Restoration Architecture", value: "Restoration Architecture" },
        { label: "Healthcare Architecture", value: "Healthcare Architecture" },
        { label: "Educational Architecture", value: "Educational Architecture" },
        { label: "Retail Architecture", value: "Retail Architecture" },
        { label: "Religious Architecture", value: "Religious Architecture" },
        { label: "Transportation Architecture", value: "Transportation Architecture" },
        { label: "Civic Architecture", value: "Civic Architecture" },
      ],
      Grouting: [
        { label: "Epoxy Grouting", value: "Epoxy Grouting" },
        { label: "Cementitious Grouting", value: "Cementitious Grouting" },
        { label: "Chemical Grouting", value: "Chemical Grouting" },
        { label: "Polyurethane Grouting", value: "Polyurethane Grouting" },
        { label: "Permeation Grouting", value: "Permeation Grouting" },
        { label: "Compaction Grouting", value: "Compaction Grouting" },
        { label: "Pressure Grouting", value: "Pressure Grouting" },
        { label: "Microfine Grouting", value: "Microfine Grouting" },
        { label: "Injection Grouting", value: "Injection Grouting" },
      ],
      Excavation: [
        { label: "Site Preparation", value: "Site Preparation" },
        { label: "Trenching", value: "Trenching" },
        { label: "Grading and Land Leveling", value: "Grading and Land Leveling" },
        { label: "Foundation Excavation", value: "Foundation Excavation" },
        { label: "Basement Excavation", value: "Basement Excavation" },
        { label: "Roadway Excavation", value: "Roadway Excavation" },
        { label: "Pool Excavation", value: "Pool Excavation" },
        { label: "Drainage Excavation", value: "Drainage Excavation" },
        { label: "Demolition Excavation", value: "Demolition Excavation" },
        { label: "Dredging", value: "Dredging" },
        { label: "Rock Excavation", value: "Rock Excavation" },
        { label: "Utility Excavation", value: "Utility Excavation" },
        { label: "Earthmoving", value: "Earthmoving" },
      ],
      Carpentry: [
        { label: "Finish Carpentry", value: "Finish Carpentry" },
        { label: "Framing Carpentry", value: "Framing Carpentry" },
        { label: "Cabinet Making", value: "Cabinet Making" },
        { label: "Trim and Molding Installation", value: "Trim and Molding Installation" },
        { label: "Custom Furniture Making", value: "Custom Furniture Making" },
        { label: "Deck Construction", value: "Deck Construction" },
        { label: "Wooden Flooring Installation", value: "Wooden Flooring Installation" },
        { label: "Door and Window Installation", value: "Door and Window Installation" },
        { label: "Shelving and Storage Solutions", value: "Shelving and Storage Solutions" },
        { label: "Staircase Construction", value: "Staircase Construction" },
        { label: "Pergola and Gazebo Construction", value: "Pergola and Gazebo Construction" },
        { label: "Wood Repair and Restoration", value: "Wood Repair and Restoration" },
        { label: "Exterior Siding Installation", value: "Exterior Siding Installation" },
      ], Roofing: [
        { label: "Asphalt Shingle Roofing", value: "Asphalt Shingle Roofing" },
        { label: "Metal Roofing", value: "Metal Roofing" },
        { label: "Tile Roofing", value: "Tile Roofing" },
        { label: "Flat Roofing", value: "Flat Roofing" },
        { label: "Slate Roofing", value: "Slate Roofing" },
        { label: "Wood Shake Roofing", value: "Wood Shake Roofing" },
        { label: "Roof Installation", value: "Roof Installation" },
        { label: "Roof Replacement", value: "Roof Replacement" },
        { label: "Roof Repair", value: "Roof Repair" },
        { label: "Roof Inspection", value: "Roof Inspection" },
        { label: "Gutter Installation/Repair", value: "Gutter Installation/Repair" },
        { label: "Green Roofing", value: "Green Roofing" },
        { label: "Solar Roofing", value: "Solar Roofing" },
      ],Plumbing: [
        { label: "Residential Plumbing", value: "Residential Plumbing" },
        { label: "Commercial Plumbing", value: "Commercial Plumbing" },
        { label: "Emergency Plumbing", value: "Emergency Plumbing" },
        { label: "Water Heater Installation/Repair", value: "Water Heater Installation/Repair" },
        { label: "Pipe Installation and Repair", value: "Pipe Installation and Repair" },
        { label: "Sewer Line Installation/Repair", value: "Sewer Line Installation/Repair" },
        { label: "Drain Cleaning", value: "Drain Cleaning" },
        { label: "Gas Line Installation/Repair", value: "Gas Line Installation/Repair" },
        { label: "Leak Detection and Repair", value: "Leak Detection and Repair" },
        { label: "Bathroom/Kitchen Plumbing", value: "Bathroom/Kitchen Plumbing" },
        { label: "Water Filtration Systems", value: "Water Filtration Systems" },
        { label: "Backflow Prevention", value: "Backflow Prevention" },
      ],Electrical: [
        { label: "Residential Electrical", value: "Residential Electrical" },
        { label: "Commercial Electrical", value: "Commercial Electrical" },
        { label: "Industrial Electrical", value: "Industrial Electrical" },
        { label: "Low Voltage Wiring", value: "Low Voltage Wiring" },
        { label: "Electrical Panel Upgrade", value: "Electrical Panel Upgrade" },
        { label: "Lighting Installation", value: "Lighting Installation" },
        { label: "Backup Generator Installation", value: "Backup Generator Installation" },
        { label: "EV Charger Installation", value: "EV Charger Installation" },
        { label: "Home Automation Wiring", value: "Home Automation Wiring" },
        { label: "Solar Panel Installation", value: "Solar Panel Installation" },
        { label: "Electrical Inspections", value: "Electrical Inspections" },
      ],PipeLine: [
        { label: "Water Supply Pipeline", value: "Water Supply Pipeline" },
        { label: "Sewer Pipeline", value: "Sewer Pipeline" },
        { label: "Oil Pipeline", value: "Oil Pipeline" },
        { label: "Gas Pipeline", value: "Gas Pipeline" },
        { label: "Stormwater Drainage Pipeline", value: "Stormwater Drainage Pipeline" },
        { label: "Industrial Pipeline", value: "Industrial Pipeline" },
        { label: "Irrigation Pipeline", value: "Irrigation Pipeline" },
        { label: "Telecommunication Cable Pipeline", value: "Telecommunication Cable Pipeline" },
      ],Foundation: [
        { label: "Concrete Slab Foundation", value: "Concrete Slab Foundation" },
        { label: "Crawl Space Foundation", value: "Crawl Space Foundation" },
        { label: "Basement Foundation", value: "Basement Foundation" },
        { label: "Pier and Beam Foundation", value: "Pier and Beam Foundation" },
        { label: "Poured Concrete Foundation", value: "Poured Concrete Foundation" },
        { label: "Block Foundation", value: "Block Foundation" },
        { label: "Post-Tension Foundation", value: "Post-Tension Foundation" },
        { label: "Stone Foundation", value: "Stone Foundation" },
      ],
      Concrete: [
        { label: "Concrete Floors", value: "Concrete Floors" },
        { label: "Concrete Countertops", value: "Concrete Countertops" },
        { label: "Garage Floor Coatings", value: "Garage Floor Coatings" },
        { label: "Furniture, Sinks, Fire Bowls", value: "Furniture, Sinks, Fire Bowls" },
        { label: "Basement Floors", value: "Basement Floors" },

        { label: "Concrete Patios", value: "Concrete Patios" },
        { label: "Concrete Driveways", value: "Concrete Driveways" },
        { label: "Concrete Pool Decks", value: "Concrete Pool Decks" },
        { label: "Outdoor Kitchens & Counters", value: "Outdoor Kitchens & Counters" },
        { label: "Outdoor Fireplace", value: "Outdoor Fireplace" },
        { label: "Concrete Walkways", value: "Concrete Walkways" },
      ],

    Painting: [
        { label: "Wall Painting", value: "Wall Painting" },
        { label: "Ceiling Painting", value: "Ceiling Painting" },
        { label: "Trim & Molding Painting", value: "Trim & Molding Painting" },
        { label: "Cabinet Painting", value: "Cabinet Painting" },
        { label: "Wallpaper Installation/Removal", value: "Wallpaper Installation/Removal" },
        { label: "Accent Walls", value: "Accent Walls" },

        { label: "House Exterior Painting", value: "House Exterior Painting" },
        { label: "Deck & Fence Painting", value: "Deck & Fence Painting" },
        { label: "Exterior Trim Painting", value: "Exterior Trim Painting" },
        { label: "Garage Door Painting", value: "Garage Door Painting" },
        { label: "Siding Painting", value: "Siding Painting" },
        { label: "Shutter Painting", value: "Shutter Painting" },
      ],
      InteriorDesign: [
        { label: "Residential Interior Design", value: "Residential Interior Design" },
        { label: "Commercial Interior Design", value: "Commercial Interior Design" },
        { label: "Hospitality Design", value: "Hospitality Design" },
        { label: "Office Space Design", value: "Office Space Design" },
        { label: "Retail Space Design", value: "Retail Space Design" },
        { label: "Kitchen and Bath Design", value: "Kitchen and Bath Design" },
        { label: "Space Planning", value: "Space Planning" },
        { label: "Furniture Design", value: "Furniture Design" },
      ],
      ExteriorDesign: [
        { label: "Landscape Design", value: "Landscape Design" },
        { label: "Facade Design", value: "Facade Design" },
        { label: "Site Planning", value: "Site Planning" },
        { label: "Outdoor Living Spaces", value: "Outdoor Living Spaces" },
        { label: "Lighting Design", value: "Lighting Design" },
        { label: "Swimming Pool Design", value: "Swimming Pool Design" },
        { label: "Hardscape Design", value: "Hardscape Design" },
      ],
      Renovation: [
        { label: "Kitchen Renovation", value: "Kitchen Renovation" },
        { label: "Bathroom Renovation", value: "Bathroom Renovation" },
        { label: "Whole House Renovation", value: "Whole House Renovation" },
        { label: "Historic Renovation", value: "Historic Renovation" },
        { label: "Commercial Renovation", value: "Commercial Renovation" },
        { label: "Room Additions", value: "Room Additions" },
        { label: "Basement Finishing", value: "Basement Finishing" },
        { label: "Exterior Renovation", value: "Exterior Renovation" },
      ],
   
  };
  
  export default typesOfWorks;
  